### ISSUE TITLE
does it work on free version of linq?

### ISSUE THREAD

**Issue by minhe7735** [rdady/gear-vr-controller-windows#1]
got these error when trying to run it. No nuget package prompts either.
```
CS0731 The type forwarder for type 'Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic' in assembly 'Windows' causes a cycle

CS1069 The type name 'GattCharacteristic' could not be found in the namespace 'Windows.Devices.Bluetooth.GenericAttributeProfile'. This type has been forwarded to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime' Consider adding a reference to that assembly.

CS0731 The type forwarder for type 'Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs' in assembly 'Windows' causes a cycle

CS1069 The type name 'GattValueChangedEventArgs' could not be found in the namespace 'Windows.Devices.Bluetooth.GenericAttributeProfile'. This type has been forwarded to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime' Consider adding a reference to that assembly.
```

**Comment by rdady** [comment]
LinqPad free and paid version don't differ in means of what code they execute.
I will add to the readme the configuration separately, not that it gets lost in the .linq file or so.

**Comment by minhe7735** [comment]
I fixed it by changing the path for the 3 `.winmd ` references since it was different for my pc and manually downloaded audio switcher dlls.
Had to comment out `capdevice?.Mute(!capdevice.IsMuted);` or it would give this error.
`CS1061 'CoreAudioDevice' does not contain a definition for 'Mute' and no extension method 'Mute' accepting a first argument of type 'CoreAudioDevice' could be found (press F4 to add a using directive or assembly reference)`

**Comment by rdady** [comment]
Does it work now?

**Comment by minhe7735** [comment]
Yes, works just fine now. Since I won't be using `ToggleMic()`.

**Comment by saveoil1982** [comment]
works fine after change MAC of gearvr controller (maybe mark it in readme?) , but very lag (intel N5000 CPU is too poor?)

**Comment by rdady** [comment]
I'm not sure about minimum hardware specs, but MAC is a good point, I'll add it to meadme.

**Comment by rdady** [comment]
Closed.
