### ISSUE TITLE
The type or namespace name 'Windows' could not be found

### ISSUE THREAD

**Issue by Matatoskr** [rdady/gear-vr-controller-windows#4]
I'm guessig i dont have the correct NuGet? Which ones do I need? Linqpad didn't ask to download the ones I'm missing.

I'm not too sure if I'm right here as my knowledge on coding is very basic

**Comment by rdady** [comment]
Windows 11 has not yet been tested. I don't have the hardware required for Windows 11.

**Comment by Matatoskr** [comment]
Hey thanks for the reply. Im going to test it.. Im just having a problem with linkpad and the nugets. Wont automatically download The needed nugets :(
